name: ci

on:
  push:
    branches: [develop, qa, main, hu-res-ui-dev]
  pull_request:
    branches: [develop, qa, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - run: npm ci
      - run: npm run build
